### ISSUE TITLE
STM32G0x - SPI frame datasize logic is different than for other families

### ISSUE THREAD

**Issue by hepoun** [libopencm3/libopencm3#1442] opened 2022-10-18 11:42 UTC
For STM32G0 there is a data packing feature which is used automatically when data frame size fits into one byte and a 16b write into SPIx_DR is done, see [STM32G0x1 advanced Arm®-based 32-bit MCUs - Reference manual](https://www.st.com/resource/en/reference_manual/rm0444-stm32g0x1-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) the section 35.5.9 (and there the _Data packing_ paragraph), as a consequence the `spi_xfer()` as it is now doesn't work for datasizes <= 8b, it will always clock two frames because internally it writes 16b into SPIx_DR.

I guess for STM32G0 we need to use SPIx_DR8 for datasizes <= 8b (maybe `spi_xfer8()` function?).

**Comment by karlp** [comment] 2022-10-18 14:37
Duplicate of #318

**Closed by karlp** 2022-10-18 14:37 UTC
