### ISSUE TITLE
STM32F2\4 crypto bug

### ISSUE THREAD

**Issue by konachan700** [libopencm3/libopencm3#797] opened 2017-06-09 15:49 UTC
Hello!
In file "crypto_common_f24.c" in the line 144 I found a bug:
`#define CRYP_IVR(i)             MMIO32(CRYP_BASE + 0x40 + (i) * 8)`
The correct value is:
`#define CRYP_IVR(i)             MMIO32(CRYP_BASE + 0x40 + (i) * 4)`
or:
`#define CRYP_IVR(i)             MMIO64(CRYP_BASE + 0x40 + (i) * 8)`

Please, fix this code. 
The problem is very difficult to find, this leads to an undefined behavior with 256-bit encryption.

**Comment by karlp** [comment] 2017-06-10 13:19
Duplicate of https://github.com/libopencm3/libopencm3/pull/794

**Closed by karlp** 2017-06-10 13:19 UTC
