### ISSUE TITLE
Signedness of adc_read_injected()

### ISSUE THREAD

**Issue by jsphuebner** [libopencm3/libopencm3#967] opened 2018-09-17 14:40 UTC
When the function adc_set_injected_offset() is used then the content of ADC_JDRx is in twos complement format. The signature of adc_read_injected() should thus be signed and ADC_JDRx must be casted to signed as well.
```

-uint32_t adc_read_injected(uint32_t adc, uint8_t reg)
+int32_t adc_read_injected(uint32_t adc, uint8_t reg)
 {
 	switch (reg) {
 	case 1:
-		return ADC_JDR1(adc);
+		return (int16_t)ADC_JDR1(adc);
 	case 2:
-		return ADC_JDR2(adc);
+		return (int16_t)ADC_JDR2(adc);
 	case 3:
-		return ADC_JDR3(adc);
+		return (int16_t)ADC_JDR3(adc);
 	case 4:
-		return ADC_JDR4(adc);
+		return (int16_t)ADC_JDR4(adc);
 	}
 	return 0;
 }
```

**Comment by karlp** [comment] 2018-09-17 17:16
Duplicate of https://github.com/libopencm3/libopencm3/pull/285

**Closed by karlp** 2018-09-17 17:16 UTC
